<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>AnnoTape.App</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../AnnoTape.Core/AnnoTape.Core.csproj" />
    <PackageReference Include="CupriFace" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets/AnnoTape.html" LogicalName="AnnoTape.App.Assets.AnnoTape.html" />
    <EmbeddedResource Include="Assets/AnnoTape.css" LogicalName="AnnoTape.App.Assets.AnnoTape.css" />
    <EmbeddedResource Include="Assets/annotape-icon.png" LogicalName="Assets/annotape-icon.png" />
    <EmbeddedResource Include="Assets/empty-measurement.png" LogicalName="Assets/empty-measurement.png" />
  </ItemGroup>
</Project>
